name: ArathothI
version: 1.1-SNAPSHOT
main: ink.rainbowbridge.v1.arathoth.ArathothI
softdepend: [ PlaceHolderAPI ]
authors: [ Freeze003 ]
description: Powerful Item-Attribute Plugin
website: github.com/Freeze003/Arathoth-I
commands:
  Arathoth:
    usage: /Arathoth
    aliases: [ Ara ]
