name: ArathothI
version: 1.11-SNAPSHOT
main: ink.rainbowbridge.v1.arathoth.ArathothI
softdepend: [ PlaceHolderAPI ]
authors: [ 寒雨 ]
description: Powerful Item-Attribute Plugin
website: github.com/Freeze003/Arathoth-I
commands:
  Arathoth:
    usage: /Arathoth
    aliases: [ Ara ]
